- name: "Get Perl installation directory"
  shell: perldoc -l Path::Tiny | sed 's|/Path/Tiny.pm||'
  register: perl_install_dir
  changed_when: false # idempotency requirement

- name: "Add group 'octopussy'"
  group:
    name: "{{ octopussy_groupname }}"
    system: yes

- name: "Add user 'octopussy'"
  user:
    name: "{{ octopussy_username }}"
    system: yes
    createhome: no

- name: "Create destination directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - /etc/aat/
    - /etc/octopussy/
    - /usr/share/aat/
    - "{{ octopussy_dir_web }}"
    - "{{ perl_install_dir.stdout }}/AAT/"
    - "{{ perl_install_dir.stdout }}/Octopussy/"
    - /var/lib/octopussy/
    - /var/run/aat/
    - "{{ octopussy_dir_run }}"

- name: "Get list of octopussy 'bin' files"
  find:
    paths: /tmp/octopussy/bin
  register: find_octo_bin_files

- name: "Copy octopussy 'bin' files"
  copy:
    src: "{{ item.path }}"
    dest: "{{ octopussy_dir_bin }}"
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ find_octo_bin_files.files }}"

- name: "Get list of octopussy 'etc', 'usr_share_aat', 'var_lib' directories"
  find:
    paths:
      - /tmp/octopussy/etc
      - /tmp/octopussy/usr/share/aat
      - /tmp/octopussy/var/lib/octopussy
    file_type: directory
    recurse: yes
  register: find_octo_various_dirs

- name: "Create directories for 'etc', 'usr_share_aat', 'var_lib'"
  file:
    state: directory
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ find_octo_various_dirs.files }}"

- name: "Get list of octopussy 'etc', 'usr_share_aat', 'var_lib' files"
  find:
    paths: 
      - /tmp/octopussy/etc
      - /tmp/octopussy/usr/share/aat
      - /tmp/octopussy/var/lib/octopussy
    recurse: yes
  register: find_octo_various_files

- name: "Copy octopussy 'etc', 'usr_share_aat', 'var_lib' files"
  copy:
    src: "{{ item.path }}"
    dest: "{{ item.path | regex_replace('/tmp/octopussy', '') }}"
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ find_octo_various_files.files }}"

- name: "Get list of octopussy 'lib' directories"
  find:
    paths: /tmp/octopussy/lib
    file_type: directory
    recurse: yes
  register: find_octo_lib_dirs

- name: "Create directories for 'lib'"
  file:
    state: directory
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ find_octo_lib_dirs.files }}"

- name: "Get list of octopussy 'lib' files"
  find:
    paths: /tmp/octopussy/lib
    recurse: yes
  register: find_octo_lib

- name: "Copy octopussy 'lib' files"
  copy:
    src: "{{ item.path }}"
    dest: "{{ perl_install_dir.stdout }}/{{ item.path | regex_replace('/tmp/octopussy/lib/', '') }}"
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ find_octo_lib.files }}"

- name: "Get list of octopussy 'web' directories"
  find:
    paths: /tmp/octopussy/usr/share/octopussy
    file_type: directory
    recurse: yes
  register: find_octo_web_dirs

- name: "Create directories for 'web'"
  file:
    state: directory
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ find_octo_web_dirs.files }}"

- name: "Get list of octopussy 'web' files"
  find:
    paths: /tmp/octopussy/usr/share/octopussy
    recurse: yes
  register: find_octo_web

- name: "Copy octopussy 'web' files"
  copy:
    src: "{{ item.path }}"
    dest: "{{ octopussy_dir_web }}/{{ item.path | regex_replace('/tmp/octopussy/usr/share/octopussy/', '') }}"
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ find_octo_web.files }}"

- name: "chown directories"
  file:
    name: "{{ item }}"
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
    recurse: yes
  with_items:
    - /var/run/aat
    - "{{ octopussy_dir_run }}"

- name: "Changes files rights 0644 for AAT.pm & Octopussy.pm"
  file:
    name: "{{ item }}"
    mode: 0644
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  with_items:
    - "{{ perl_install_dir.stdout }}/AAT.pm"
    - "{{ perl_install_dir.stdout }}/Octopussy.pm"

- name: "Changes files rights 0644 for AAT/ & Octopussy/"
  file:
    name: "{{ item }}"
    state: directory
    mode: 0644
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
    recurse: yes
  with_items:
    - "{{ perl_install_dir.stdout }}/AAT"
    - "{{ perl_install_dir.stdout }}/Octopussy"

- name: "Changes directory rights for AAT & Octopussy"
  file:
    name: "{{ item }}"
    state: directory
    mode: a+X
    recurse: yes
  with_items:
    - "{{ perl_install_dir.stdout }}/AAT"
    - "{{ perl_install_dir.stdout }}/Octopussy"

- name: "Select apache2.conf for 'Debian' family"
  command: mv /etc/octopussy/apache2_debian.conf /etc/octopussy/apache2.conf
  when:
    - ansible_os_family == 'Debian'

- name: "Set apache2.conf for 'not Debian family"
  command: mv /etc/octopussy/apache2_other.conf /etc/octopussy/apache2.conf
  when:
    - ansible_os_family != 'Debian'

- name: "create symlink /etc/init.d/octopussy -> /usr/sbin/octopussy"
  file:
    src: /usr/sbin/octopussy
    dest: /etc/init.d/octopussy
    state: link

- name: "Add octo_logrotate to cron.daily"
  template:
    src: cron.daily.j2
    dest: /etc/cron.daily/octo_logrotate
    owner: "{{ octopussy_username }}"
    group: "{{ octopussy_groupname }}"
  tags: cron

- name: "Enable 'octopussy' service"
  service:
    name: octopussy
    enabled: yes
  notify:
    - restart service octopussy
