- name: "rsyslog - enable support for local system logging"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '$ModLoad imuxsock' 
    line: '$ModLoad imuxsock # provides support for local system logging'

- name: "rsyslog - enable support for systemd journal"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '$ModLoad imjournal'
    line: '$ModLoad imjournal # provides access to the systemd journal'

- name: "rsyslog - provides UDP syslog reception"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '$ModLoad imudp'
    line: '$ModLoad imudp'

- name: "rsyslog - provides TCP syslog reception"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '$ModLoad imtcp'
    line: '$ModLoad imtcp'

- name: "rsyslog - disable default timestamp format"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
    line: '#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'

- name: "rsyslog - include all config files in /etc/rsyslog.d/"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '$IncludeConfig /etc/rsyslog.d/*.conf'
    line: '$IncludeConfig /etc/rsyslog.d/*.conf'

- name: "Delete 'syslog' service"
  service:
    name: syslog
    state: absent

- name: "Enable 'rsyslog' service"
  service:
    name: rsyslog
    state: enabled
